//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionCalculator.UI.Test.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstructionDataContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstructionDataContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConstructionCalculator.UI.Test.Localization.ConstructionDataContextResources", typeof(ConstructionDataContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Feature.
        /// </summary>
        public static string BusinessFeature {
            get {
                return ResourceManager.GetString("BusinessFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Value.
        /// </summary>
        public static string BusinessFeature_BusinessValue {
            get {
                return ResourceManager.GetString("BusinessFeature_BusinessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string BusinessFeature_File {
            get {
                return ResourceManager.GetString("BusinessFeature_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定,Qi.
        /// </summary>
        public static string BusinessFeature_GdQi {
            get {
                return ResourceManager.GetString("BusinessFeature_GdQi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动因子a.
        /// </summary>
        public static string BusinessFeature_Hdyza {
            get {
                return ResourceManager.GetString("BusinessFeature_Hdyza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火灾蔓延因子i.
        /// </summary>
        public static string BusinessFeature_Hzmyyzi {
            get {
                return ResourceManager.GetString("BusinessFeature_Hzmyyzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业态特征编号.
        /// </summary>
        public static string BusinessFeature_Id {
            get {
                return ResourceManager.GetString("BusinessFeature_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价值因子.
        /// </summary>
        public static string BusinessFeature_Jzyz {
            get {
                return ResourceManager.GetString("BusinessFeature_Jzyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业态特征.
        /// </summary>
        public static string BusinessFeature_Name {
            get {
                return ResourceManager.GetString("BusinessFeature_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人口密度取值.
        /// </summary>
        public static string BusinessFeature_Rkmdqz {
            get {
                return ResourceManager.GetString("BusinessFeature_Rkmdqz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疏散人数密度*单层（单元）面积.
        /// </summary>
        public static string BusinessFeature_Ssrs {
            get {
                return ResourceManager.GetString("BusinessFeature_Ssrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疏散时间修正值P.
        /// </summary>
        public static string BusinessFeature_Sssjxzzp {
            get {
                return ResourceManager.GetString("BusinessFeature_Sssjxzzp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动,Qm.
        /// </summary>
        public static string BusinessFeature_YdQm {
            get {
                return ResourceManager.GetString("BusinessFeature_YdQm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依赖因子d.
        /// </summary>
        public static string BusinessFeature_Ylyzd {
            get {
                return ResourceManager.GetString("BusinessFeature_Ylyzd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Features.
        /// </summary>
        public static string BusinessFeaturePlural {
            get {
                return ResourceManager.GetString("BusinessFeaturePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Value.
        /// </summary>
        public static string BusinessValue {
            get {
                return ResourceManager.GetString("BusinessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string BusinessValue_File {
            get {
                return ResourceManager.GetString("BusinessValue_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业态编号.
        /// </summary>
        public static string BusinessValue_Id {
            get {
                return ResourceManager.GetString("BusinessValue_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业态名称.
        /// </summary>
        public static string BusinessValue_Name {
            get {
                return ResourceManager.GetString("BusinessValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Values.
        /// </summary>
        public static string BusinessValuePlural {
            get {
                return ResourceManager.GetString("BusinessValuePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Mapping.
        /// </summary>
        public static string CellMapping {
            get {
                return ResourceManager.GetString("CellMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel列序号.
        /// </summary>
        public static string CellMapping_ColumnExcelNumber {
            get {
                return ResourceManager.GetString("CellMapping_ColumnExcelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列名称.
        /// </summary>
        public static string CellMapping_ColumnName {
            get {
                return ResourceManager.GetString("CellMapping_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列序号.
        /// </summary>
        public static string CellMapping_ColumnNumber {
            get {
                return ResourceManager.GetString("CellMapping_ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小数位数.
        /// </summary>
        public static string CellMapping_Digital {
            get {
                return ResourceManager.GetString("CellMapping_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string CellMapping_File {
            get {
                return ResourceManager.GetString("CellMapping_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公式.
        /// </summary>
        public static string CellMapping_Formula {
            get {
                return ResourceManager.GetString("CellMapping_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分类.
        /// </summary>
        public static string CellMapping_Group {
            get {
                return ResourceManager.GetString("CellMapping_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CellMapping_Id {
            get {
                return ResourceManager.GetString("CellMapping_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Mappings.
        /// </summary>
        public static string CellMappingPlural {
            get {
                return ResourceManager.GetString("CellMappingPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元单层安全出口宽度cm.
        /// </summary>
        public static string Construction_Aqckkd {
            get {
                return ResourceManager.GetString("Construction_Aqckkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元单层安全出口数量.
        /// </summary>
        public static string Construction_Aqcksl {
            get {
                return ResourceManager.GetString("Construction_Aqcksl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Feature.
        /// </summary>
        public static string Construction_BusinessFeature {
            get {
                return ResourceManager.GetString("Construction_BusinessFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Value.
        /// </summary>
        public static string Construction_ConstructionValue {
            get {
                return ResourceManager.GetString("Construction_ConstructionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层数.
        /// </summary>
        public static string Construction_Cs {
            get {
                return ResourceManager.GetString("Construction_Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 栋数.
        /// </summary>
        public static string Construction_Ds {
            get {
                return ResourceManager.GetString("Construction_Ds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单体编号.
        /// </summary>
        public static string Construction_Dtbh {
            get {
                return ResourceManager.GetString("Construction_Dtbh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元单层建筑面积m2.
        /// </summary>
        public static string Construction_Dydcjzmj {
            get {
                return ResourceManager.GetString("Construction_Dydcjzmj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Construction_File {
            get {
                return ResourceManager.GetString("Construction_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高度m.
        /// </summary>
        public static string Construction_Gd {
            get {
                return ResourceManager.GetString("Construction_Gd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Construction_Id {
            get {
                return ResourceManager.GetString("Construction_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建筑名称.
        /// </summary>
        public static string Construction_Jzmc {
            get {
                return ResourceManager.GetString("Construction_Jzmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总建筑面积m2.
        /// </summary>
        public static string Construction_Jzmj {
            get {
                return ResourceManager.GetString("Construction_Jzmj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可临近面.
        /// </summary>
        public static string Construction_Kljm {
            get {
                return ResourceManager.GetString("Construction_Kljm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 灭火器.
        /// </summary>
        public static string Construction_Mhq {
            get {
                return ResourceManager.GetString("Construction_Mhq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 喷淋.
        /// </summary>
        public static string Construction_Pl {
            get {
                return ResourceManager.GetString("Construction_Pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室内栓.
        /// </summary>
        public static string Construction_Sns {
            get {
                return ResourceManager.GetString("Construction_Sns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室外栓最近距离 (m).
        /// </summary>
        public static string Construction_Swsjl {
            get {
                return ResourceManager.GetString("Construction_Swsjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 室外栓内有/无水.
        /// </summary>
        public static string Construction_Swsyws {
            get {
                return ResourceManager.GetString("Construction_Swsyws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水源、水池、水箱.
        /// </summary>
        public static string Construction_Sy {
            get {
                return ResourceManager.GetString("Construction_Sy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现役消防部队距片区距离(km).
        /// </summary>
        public static string Construction_Xfdjl {
            get {
                return ResourceManager.GetString("Construction_Xfdjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有无私拉乱接.
        /// </summary>
        public static string Construction_Ywsl {
            get {
                return ResourceManager.GetString("Construction_Ywsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有/无有室外栓.
        /// </summary>
        public static string Construction_Ywsws {
            get {
                return ResourceManager.GetString("Construction_Ywsws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有无维保记录.
        /// </summary>
        public static string Construction_Ywwbjl {
            get {
                return ResourceManager.GetString("Construction_Ywwbjl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总出口宽度cm.
        /// </summary>
        public static string Construction_Zckkd {
            get {
                return ResourceManager.GetString("Construction_Zckkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总出口数量.
        /// </summary>
        public static string Construction_Zcksl {
            get {
                return ResourceManager.GetString("Construction_Zcksl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动报警.
        /// </summary>
        public static string Construction_Zdbj {
            get {
                return ResourceManager.GetString("Construction_Zdbj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructions.
        /// </summary>
        public static string ConstructionPlural {
            get {
                return ResourceManager.GetString("ConstructionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Value.
        /// </summary>
        public static string ConstructionValue {
            get {
                return ResourceManager.GetString("ConstructionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级.
        /// </summary>
        public static string ConstructionValue_DesignRequirement {
            get {
                return ResourceManager.GetString("ConstructionValue_DesignRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string ConstructionValue_File {
            get {
                return ResourceManager.GetString("ConstructionValue_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ConstructionValue_Id {
            get {
                return ResourceManager.GetString("ConstructionValue_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结构抗火时间，fs(min).
        /// </summary>
        public static string ConstructionValue_Jgkhsj {
            get {
                return ResourceManager.GetString("ConstructionValue_Jgkhsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结构抗火因子，F0.
        /// </summary>
        public static string ConstructionValue_Jgkhyz {
            get {
                return ResourceManager.GetString("ConstructionValue_Jgkhyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建筑抗火因子，F.
        /// </summary>
        public static string ConstructionValue_Jzkhyz {
            get {
                return ResourceManager.GetString("ConstructionValue_Jzkhyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        public static string ConstructionValue_Name {
            get {
                return ResourceManager.GetString("ConstructionValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内墙抗火时间,fw(min).
        /// </summary>
        public static string ConstructionValue_Nqkhsj {
            get {
                return ResourceManager.GetString("ConstructionValue_Nqkhsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均抗火能力，f.
        /// </summary>
        public static string ConstructionValue_Pjkhnl {
            get {
                return ResourceManager.GetString("ConstructionValue_Pjkhnl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屋顶和吊顶抗火时间,fd(min).
        /// </summary>
        public static string ConstructionValue_Wdkhsj {
            get {
                return ResourceManager.GetString("ConstructionValue_Wdkhsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外墙抗火时间,ff(min).
        /// </summary>
        public static string ConstructionValue_Wqkhsj {
            get {
                return ResourceManager.GetString("ConstructionValue_Wqkhsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Values.
        /// </summary>
        public static string ConstructionValuePlural {
            get {
                return ResourceManager.GetString("ConstructionValuePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string File_Description {
            get {
                return ResourceManager.GetString("File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string File_FileName {
            get {
                return ResourceManager.GetString("File_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string File_Id {
            get {
                return ResourceManager.GetString("File_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string File_Type {
            get {
                return ResourceManager.GetString("File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FilePlural {
            get {
                return ResourceManager.GetString("FilePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Level.
        /// </summary>
        public static string RiskLevel {
            get {
                return ResourceManager.GetString("RiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string RiskLevel_Color {
            get {
                return ResourceManager.GetString("RiskLevel_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 说明.
        /// </summary>
        public static string RiskLevel_Description {
            get {
                return ResourceManager.GetString("RiskLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string RiskLevel_File {
            get {
                return ResourceManager.GetString("RiskLevel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string RiskLevel_Id {
            get {
                return ResourceManager.GetString("RiskLevel_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大值.
        /// </summary>
        public static string RiskLevel_MaxValue {
            get {
                return ResourceManager.GetString("RiskLevel_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小值.
        /// </summary>
        public static string RiskLevel_MinValue {
            get {
                return ResourceManager.GetString("RiskLevel_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Levels.
        /// </summary>
        public static string RiskLevelPlural {
            get {
                return ResourceManager.GetString("RiskLevelPlural", resourceCulture);
            }
        }
    }
}
